### ISSUE TITLE
When inserting a disc to rip, it sees the disc, then immediately says it's done ripping and ejects the disc

### ISSUE THREAD

**Issue by jevansoh** [thecreativeone91/DVDFabAutoRip#8]
I installed the script as a service with admin privileges.

I double checked the drive letters and that the script referred to the proper drive letters/folders.

When I insert a disc, it sees it, then immediately says that ripping has finished and ejects the disc.

It doesn't leave a file behind of any size and doesn't create anything.

I don't know what else to do to get it to actually rip the disc before ejecting.

I've tried multiple discs, both DVD and Blu-Ray.

**Comment by thecreativeone91** [comment]
Do you have DVDFab installed under C:\Program Files\DVDFab\DVDFab 12\DVDFab64.exe I believe you may need to activate it at least with a trial license as well. 

You may need to install PowerShell 7 on certain operating systems if not already installed.

Try stopping the service and manually running the script and see if the DVDFab interface is opening.

**Comment by jevansoh** [comment]
I have DVDFab installed in that exact location and I have purchased it.  I
have a one-year license and it is active.

I'm using Windows 11 for reference.

I downloaded PowerShell 7, stopped the service, and ran the script -install
to set up the service again.

When I insert a disc, DVDFab reads and recognizes it, it shows the
title/info in DVDFab, then as soon as DVDFab finishes
recognizing/initializing the media, the disc tray opens and the script says
it's done copying.

I've tried each of the steps you outline and greatly appreciate your help,
but I'm afraid it still isn't working.

Do you have any further suggestions?

Thanks,

--J

**Comment by thecreativeone91** [comment]
> I have DVDFab installed in that exact location and I have purchased it. I have a one-year license and it is active. I'm using Windows 11 for reference. I downloaded PowerShell 7, stopped the service, and ran the script -install to set up the service again. When I insert a disc, DVDFab reads and recognizes it, it shows the title/info in DVDFab, then as soon as DVDFab finishes recognizing/initializing the media, the disc tray opens and the script says it's done copying. I've tried each of the steps you outline and greatly appreciate your help, but I'm afraid it still isn't working. Do you have any further suggestions? Thanks,
> […](#)

I Tested on a windows 11 VM and was only able to reproduce this when the `$Dest=` folder was either a non-valid directory or a directory DVDFab does not have access to. DVDFab itself crashes out, closing the DVDFab64.exe process the script waits for and then ejects. DVDFab itself handles the path and actual ripping once opened.

**Comment by jevansoh** [comment]
Thank you for testing further.

I just double checked the output directory and noticed something I didn't
notice before.  There actually is a file that was created in the output
directory (F:\DVDFAB_RIPS) called DVD_VIDEO.ISO but it is only 58MB in
size, so it appears it's starting to create the file but almost immediately
after beginning the process it's closing, and the script thinks it's
finished.

Since there is a small file being created in that directory, I'm assuming
access to the directory isn't an issue or there wouldn't be any file of any
size, right?

Thanks for your help in figuring this out.

--J
